spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: leir
    password: 123
    url: jdbc:postgresql://localhost:5432/blog
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 200MB
      max-file-size: 215MB
  web:
    resources:
      static-locations: classpath:/static/

socialmedia:
  jwt:
    lifetime: 15m
  "reading-speed": 250
  files:
    "basic-directory": D:\projects\social-media\s3files
    mime-type-to-valid-extension:
      "[image/jpeg]": [".jpeg", ".jpg", ".jpe", ".JPEG", ".JPG", ".JPE", ".jfif", ".JFIF"]
      "[image/png]": [".png", ".PNG"]
      "[image/gif]": [".gif"]
      "[video/mp4]": [".mp4", ".mp4v", ".mpg4"]


