version: '3.8'
services:
  blog:
    image: 'blog:1.0.0'
    networks:
      - blog
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  blog-postgresql:
    extends:
      file: postgresql.yml
      service: blog-postgresql
networks:
  blog: {}